version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tautulli_web_1
      APP_PORT: 8181

  web:
    image: linuxserver/tautulli:2.14.6@sha256:ac17e75ae0092a5f6dbd19e372c23239896958a6f2764bfc8b65b1f777359302
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000