version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: audiobookshelf_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/advplyr/audiobookshelf:2.15.1@sha256:9096480cb2b8cbfb3da155ea3cea5e9bfd4f3c2aae6196225c5b26d31bad1a99
    user: 1000:1000
    init: true
    restart: on-failure
    stop_grace_period: 1m
    healthcheck:
      disable: true
    environment:
      - CONFIG_PATH=/home/node/config
      - METADATA_PATH=/home/node/metadata
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/home/node/config
      - ${APP_DATA_DIR}/data/metadata:/home/node/metadata
      - ${UMBREL_ROOT}/data/storage/downloads/audiobooks:/audiobooks
      - ${UMBREL_ROOT}/data/storage/downloads/podcasts:/podcasts