version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: audiobookshelf_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/advplyr/audiobookshelf:2.18.0@sha256:e457e9d9d5df72de49d8a8d769d85b7d41359c439bfc5faec9a9e27704ea0f35
    user: 1000:1000
    init: true
    restart: on-failure
    stop_grace_period: 1m
    healthcheck:
      disable: true
    environment:
      - CONFIG_PATH=/home/node/config
      - METADATA_PATH=/home/node/metadata
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/home/node/config
      - ${APP_DATA_DIR}/data/metadata:/home/node/metadata
      - ${UMBREL_ROOT}/data/storage/downloads/audiobooks:/audiobooks
      - ${UMBREL_ROOT}/data/storage/downloads/podcasts:/podcasts