version: "3.7"

services:
  web:
    image: aceberg/watchyourlan:2.0.0@sha256:c1bc72021443ddbea860b78ffeb871ab9a3edec1b15e35413c84470eee5456f3
    network_mode: "host"        
    restart: on-failure
    stop_grace_period: 1m
    init: true
    environment:
      TZ: "UTC"
      IFACE: "eth0 wlan0 enp1s0"        # required: 1 or more interface
      DBPATH: "/data/db.sqlite"         # optional, default: /data/db.sqlite
      GUIIP: "0.0.0.0"                  # optional, default: localhost
      GUIPORT: "8840"                   # optional, default: 8840
      TIMEOUT: "120"                    # optional, time in seconds, default: 60
      THEME: "darkly"                   # optional
      IGNOREIP: "no"                    # optional
    volumes:
      - ${APP_DATA_DIR}/data:/data