version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: vaultwarden_server_1
      APP_PORT: 8089
      PROXY_AUTH_ADD: "false"

  server:
    image: vaultwarden/server:1.32.2@sha256:c07f5319d20bdbd58a19d7d779a1e97159ce25cb95572baa947c70f58589937c
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      ROCKET_PORT: 8089