version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: zabbix_zabbix-frontend_1
      APP_PORT: 8080

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:7.0.4-alpine@sha256:0856014fe6665e52530f74b5e92124eb06b2c7099e235504a130d97e599eb92c
    hostname: zabbix-frontend
    restart: on-failure
    environment:
      DB_SERVER_HOST: zabbix-database
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: UTC
    depends_on:
      - zabbix-server
      - zabbix-database

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.0.4-alpine@sha256:19de7ef209eee6663de356253c86891ba6b445c3cc1615dc5a04dda0a433e2ff
    hostname: zabbix-server
    restart: on-failure
    init: true
    environment:
      DB_SERVER_HOST: zabbix-database
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    ports:
      - "10050:10050"
    depends_on:
      - zabbix-database

  zabbix-agent:
    image: zabbix/zabbix-agent2:7.0.4-alpine@sha256:2467d406c4ac8d5f25a77d0f5b6cf12b03c1f527d575f53b552d8ff00b5e3253
    hostname: zabbix-agent
    restart: on-failure
    init: true
    environment:
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: zabbix-server

  zabbix-database:
    image: postgres:13.16-alpine3.20@sha256:e04acf5744305c9c6a19cedaa23d70a3a74b94cf62084e284793be756087aaa2
    hostname: zabbix-database
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data