services:
  app_proxy:
    environment:
      APP_HOST: navidrome_server_1
      APP_PORT: 4533
      PROXY_AUTH_ADD: "false"

  server:
    image: deluan/navidrome:0.54.1@sha256:adce9ea704d75cc4f68cc59237f299314ea04bd9fc7210d0f21932a957c97960
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music