version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pocketbase_app_1
      APP_PORT: 8090
      PROXY_AUTH_ADD: "false"
  
  app:
    image: ghcr.io/muchobien/pocketbase:0.22.25@sha256:3af86d0f99800fe8e21b36211e299022d836e0995deca5d8abadd313698bece7
    # pocketbase needs to run as root
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/data:/pb_data
      - ${APP_DATA_DIR}/data/public:/pb_public
      - ${APP_DATA_DIR}/data/hooks:/pb_hooks