version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pocketbase_app_1
      APP_PORT: 8090
      PROXY_AUTH_ADD: "false"
  
  app:
    image: ghcr.io/muchobien/pocketbase:0.23.11@sha256:cef40038fee3d4844e6cc3f56e01876c0ec05664f544a0bf112d7994c4c114de
    # pocketbase needs to run as root
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/data:/pb_data
      - ${APP_DATA_DIR}/data/public:/pb_public
      - ${APP_DATA_DIR}/data/hooks:/pb_hooks