version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pocketbase_app_1
      APP_PORT: 8090
      PROXY_AUTH_ADD: "false"
  
  app:
    image: ghcr.io/muchobien/pocketbase:0.23.4@sha256:0effb463184da3c1fe3a633e05ee2433d63e25980ced166d14a5ab518737f2b3
    # pocketbase needs to run as root
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/data:/pb_data
      - ${APP_DATA_DIR}/data/public:/pb_public
      - ${APP_DATA_DIR}/data/hooks:/pb_hooks