version: "3.7"

services:
  server:
    image: homeassistant/home-assistant:2024.11.0@sha256:0f357468558aa24858af7470f5942ae740d8472d892e7838111ee0f71110e78b
    network_mode: host
    # UI at default port 8123
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/media
      - /dev:/dev
      - /run/dbus:/run/dbus:ro