version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: openresty-manager_web_1
      APP_PORT: 34567
      
  web:
    image: uusec/openresty-manager:1.7.0@sha256:8e04537cb88a83a15d81b81951b8d881566af90d7b420e71ba5a42882d963996
    hostname: openresty-manager_web_1
    restart: on-failure
    ports:
      - 3080:80
      - 3443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data/acme:/opt/om/acme
      - ${APP_DATA_DIR}/data/data:/opt/om/data
      - ${APP_DATA_DIR}/data/conf:/opt/om/nginx/conf
    environment:
      - NGINX_RESOLVER=resolver 127.0.0.11 valid=30s ipv6=off local=on;
      - PUID=1000
      - PGID=1000
