version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: budibase_budibase_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  budibase:
    image: budibase/budibase:2.33.14@sha256:8af4b96169565ae1cc5d945da6e9f0e90691edc5cd26bf7c441774d37794c4f3
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/budibase:/data
    environment:
      JWT_SECRET: ${APP_SEED}