version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: firefox_server_1
      APP_PORT: 3000

  server:
    image: linuxserver/firefox:130.0.1@sha256:e1e5ab3a6c54cff79b66798d322dbd8ca734eb7bfd0b0e266a98a2f557e2208a
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"