version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bazarr_server_1
      APP_PORT: 6767
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/bazarr:1.5.0@sha256:c99ddc0c3a6c23edec34faf81a21fd9bdb60a02b3b5d916590b7a7e48254c87f
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure