version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: chromium_chromium_1
      APP_PORT: 3000

  chromium:
    image: ghcr.io/linuxserver/chromium:version-7a928a3a@sha256:146a12cec6c4c23dcaf87d3c7f643793d61374ff4edf7649fe2de9c6301451a5
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/config
    shm_size: "1gb"
    restart: on-failure
