version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mattermost_app_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"
  
  app:
    image: alexlack/mattermost-app:v10.1.6@sha256:354efe0457feaecae39a3abfa50452ac30075673f11f3c4016468402df1bc44e
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      MM_USERNAME: admin
      MM_PASSWORD: admin
      MM_DBNAME: mattermost
    volumes:
      - ${APP_DATA_DIR}/data/app/mattermost/config:/mattermost/config:rw
      - ${APP_DATA_DIR}/data/app/mattermost/data:/mattermost/data:rw
      - ${APP_DATA_DIR}/data/app/mattermost/logs:/mattermost/logs:rw
      - ${APP_DATA_DIR}/data/app/mattermost/plugins:/mattermost/plugins:rw
      - ${APP_DATA_DIR}/data/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8443:8443/tcp" # WebRTC over tcp
      - "8443:8443/udp" # WebRTC over udp
    depends_on:
      - db

  db:
    image: alexlack/mattermost-db:v10.1.6@sha256:0a3a4da3a4b54fa7ae1c8dcc8965a4de7569e6f256f938e1238f684d2eb7db1d
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      MM_USERNAME: admin
      MM_PASSWORD: admin
      MM_DBNAME: mattermost
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro