version: "3.7"

services:
  server:
    image: homebridge/homebridge:2024-10-09@sha256:db80af156aaefc621d5442e4b056388826a625fa2da0d8e36c429698bf949fc0
    # container runs as root
    network_mode: host
    # available at port 8581
    volumes:
      - ${APP_DATA_DIR}/data/homebridge:/homebridge
    restart: on-failure