version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: stirling-pdf_app_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api/*"
  
  app:
    image: frooodle/s-pdf:0.31.0@sha256:0200b2d18861983330e5afe91d30b8b0826b8697ca7e8e36c2c471c5265a5714
    # Stirling PDF does not work with a custom user
    #user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      # Required for extra OCR languages
      - ${APP_DATA_DIR}/data/tessdata:/usr/share/tessdata
      - ${APP_DATA_DIR}/data/configs:/configs
      - ${APP_DATA_DIR}/data/logs:/logs
    environment:
      # Not needed as Umbrel authenticates the user
      DOCKER_ENABLE_SECURITY: "false"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "true"
      LANGS: ALL