version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: syncthing_server_1
      APP_PORT: 8384

  server:
    image: syncthing/syncthing:1.28.0@sha256:30b6a53436527edf31d791361d14b1f5119cc6882dbcf07822b618ee7a74e115
    restart: on-failure
    stop_grace_period: 1m
    hostname: umbrel
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/var/syncthing
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp