version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: syncthing_server_1
      APP_PORT: 8384

  server:
    image: syncthing/syncthing:1.27.11@sha256:4ced94de2ac200921fb35ad6d01f1109f568981a12fc7666861700ab6ea70f0a
    restart: on-failure
    stop_grace_period: 1m
    hostname: umbrel
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/var/syncthing
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp