version: "3.7"

services:
  server:
    image: esphome/esphome:2024.10.2@sha256:e01bc223b5a669e559318792a9cfde6c5f69781a53a6e4c819b6499313ee5028
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure