version: "3.7"

services:
  server:
    image: esphome/esphome:2024.8.1@sha256:1eb151c380a84bf790eb1a2150dcc6cddea25f7310a44b4239de0584f37b7ff1
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure