version: "3.7"

services:
  server:
    image: esphome/esphome:2024.10.1@sha256:77680f45fd374dd08ef38626822a0f361026a9a508085f578466c549cfe0afa0
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure