version: "3.7"

services:
  server:
    image: esphome/esphome:2024.9.0@sha256:9be06e0deb0b6b7ec0af6a33f10eb064809383f018f227150dd4ed2bd766554e
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure