version: "3.7"

services:
  server:
    image: esphome/esphome:2024.11.1@sha256:f6a3f8e7a5fa562bbc50595381c3378f30ab4585ea8d1e03de237f4ba239aac3
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure