version: "3.7"

services:
  server:
    image: esphome/esphome:2024.10.0@sha256:78f7d125ecff29061cfdc14dc77d60e69532aec6b28680eba19afa72b7ac5640
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure