manifestVersion: 1
id: esphome
category: automation
name: ESPHome
version: "2024.10.0"
tagline: Intelligently manage all your ESP8266/ESP32 devices
description: >-
  ESPHome is a system to control your ESP8266/ESP32 by simple yet powerful configuration files and control them remotely through Home Automation systems.
developer: ESPHome
website: https://esphome.io
dependencies: []
repo: https://github.com/esphome/esphome
support: https://community.home-assistant.io/c/esphome
port: 6052
gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
path: ""
defaultUsername: ""
defaultPassword: ""
torOnly: false
releaseNotes: >-
  ⚠️ As usual, please check that your configurations are still working correctly after updating.


  This release includes new components, platforms, and improvements:
    - Added support for OpenTherm communication layer and hub
    - New TCA9555 GPIO driver
    - Support for Sharp GP2Y1010AU0F PM2.5 sensor
    - Added AIC3204 audio DAC component
    - New support for Seeed Grove GMxxx multichannel gas sensor
    - Added support for TE-M3200 and NPI-19 pressure sensors
    - New NAU7802 component for load cell amplifiers


  Several bug fixes and enhancements have also been implemented, including improvements to the web server, touchscreen functionality, and various component updates.


  Full release notes can be found at https://github.com/esphome/esphome/releases.
submitter: ShonP40
submission: https://github.com/getumbrel/umbrel-apps/pull/43