manifestVersion: 1
id: esphome
category: automation
name: ESPHome
version: "2024.10.1"
tagline: Intelligently manage all your ESP8266/ESP32 devices
description: >-
  ESPHome is a system to control your ESP8266/ESP32 by simple yet powerful configuration files and control them remotely through Home Automation systems.
developer: ESPHome
website: https://esphome.io
dependencies: []
repo: https://github.com/esphome/esphome
support: https://community.home-assistant.io/c/esphome
port: 6052
gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
path: ""
defaultUsername: ""
defaultPassword: ""
torOnly: false
releaseNotes: >-
  ⚠️ As usual, please check that your configurations are still working correctly after updating.


  Highlights:
    - Fixed crash with empty substitutions block.
    - Fixed broken ibeacon_uuid config in BLE RSSI.
    - Auto-load preferences on startup.
    - Added support for custom MAC addresses on Arduino.

  Full release notes can be found at https://github.com/esphome/esphome/releases.
submitter: ShonP40
submission: https://github.com/getumbrel/umbrel-apps/pull/43