version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: wireguard_app_1
      APP_PORT: 51821
  
  app:
    image: ghcr.io/wg-easy/wg-easy:15@sha256:07ed8f95eeeb4082c2e6afe3f5f3991723f496a21dd2dc25860b119a728b9ab0
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "51820:51820/udp"
    volumes:
      - ${APP_DATA_DIR}/data/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules
    environment:
      WG_HOST: ${DEVICE_DOMAIN_NAME}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
