version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: jellyseerr_server_1
      APP_PORT: 5055
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: fallenbagel/jellyseerr:2.0.1@sha256:8ff28894f9fd28bf36626fb98ddd0ee79d778de22a5dc75d69a845281e19115b
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
    restart: on-failure