version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: jellyseerr_server_1
      APP_PORT: 5055
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: fallenbagel/jellyseerr:2.0.0@sha256:319b09a7db75d697bedc41f6784efd47b8f213a26819d636dec2050efe816567
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
    restart: on-failure