version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: jellyseerr_server_1
      APP_PORT: 5055
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: fallenbagel/jellyseerr:2.2.0@sha256:7cbcd295643e2f443195b89e0c81775d19d60e84db643053a5138913d7d5e5e7
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
    restart: on-failure